######################################################################
# Automatically generated by qmake (3.0) So. Juli 27 21:51:19 2014
######################################################################

TEMPLATE = app
TARGET = octopress-gui
INCLUDEPATH += . view

# Input
HEADERS += view/blogStyle.h view/octopress_gui.h view/postList.h
SOURCES += main.cpp view/blogStyle.cpp view/octopress_gui.cpp view/postList.cpp
QT += widgets
